//
// Created by Peperodz on 6. 10. 2023.
//

#ifndef MOCKDATAGENERATOR_CCOMMASEPARATEDVALUE_H
#define MOCKDATAGENERATOR_CCOMMASEPARATEDVALUE_H


class CCommaSeparatedValue {

};


#endif //MOCKDATAGENERATOR_CCOMMASEPARATEDVALUE_H
